server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/freedel
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Vanilka125
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: zemskiy1255@gmail.com
    password: zfzheriwrixytvrc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
google:
  maps:
    api:
      key: AIzaSyDUcgXkEdhMGjFNT-0LWJ4tbsYNjXE7FkQ